spring:
  profiles:
    active: local
  application:
    name: halihali


server:
  port: 8080
  tomcat:
    max-threads: 10
    max-connections: 10

#  context-path: /
---
spring:
  profiles: local
  aop:
    auto: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  freemarker:
    cache: false
    request-context-attribute: req  #req访问request
    suffix: .tpl  #后缀名
    content-type: text/html
    enabled: true
    template-loader-path: classpath:/templates #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点

#
#  quartz:
#    properties:
#      org:
#        quartz:
#          scheduler:
#    job-store-type: memory

logging:
  config: classpath:logback-local.xml

jmeter:
  home: /Users/yefei/QA/jmeter/jmeter/apache-jmeter-5.0/

datasource:
  url: jdbc:mysql://172.16.32.243:3306/db_mock_server?useSSL=false&useUnicode=true&characterEncoding=utf8
  username: root
  password: root
  driverClassName: com.mysql.jdbc.Driver
  initialSize: 10
  maxActive: 30
  minIdle: 5
  validationQuery: SELECT 1

